name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Test CLI help
        run: node bin/cli.js --help

      - name: Test asset generation
        run: |
          node bin/cli.js -i ./logo.svg -o ./test-dist --name "Test App" --short-name "Test" --theme-color "#000000" --background-color "#ffffff"
          ls -la ./test-dist
